### ISSUE TITLE
'Home' and 'Results' links in header do not anchor anywhere 

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#17]
When I click on 'Home' or 'Results' in the header, it does not anchor the screen anywhere.   This is in all scenarios (i.e., prior to conducting a search and after conducting a search).

Browser Used: Chrome

**Comment by DRTforGSA18F** [comment]
@chriszeiders Fixed anchoring issue for the home and results button. Keep in mind the results and details anchor won't show data till a search is performed.
