### ISSUE TITLE
If I type in a search term and then click 'Search' (without hitting 'Add..." or Enter key), then search acts as if I did not type in any search term

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#19]
If I type in a search term, say "Listeria" and then click the Search button with my mouse (i.e., I do not click the "Add Listeria" link nor do I hit the Enter Key), it acts as if I did not type in any search term and shows me all 8,016 results.

If this is the default behavior for this type of input box and button, then at a minimum, we should provide instructional text above the input box telling the user to click Enter or "Add..." for the search term.  Otherwise, the user may incorrectly think that there are 8,016 results for their search.

**Comment by DRTforGSA18F** [comment]
fixed!
