### ISSUE TITLE
A search term that generates no results causes results to freeze - (Please wait...)

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#20]
Enter a search term that you expect 0 results, such as "lkjasdlkfjasldkjf".  The results freezes on a "Please wait..." modal.

![image](https://cloud.githubusercontent.com/assets/12449264/8307403/470abefe-198c-11e5-8bac-de644b4b0111.png)

**Comment by DRTforGSA18F** [comment]
This issue has been addressed.
