### ISSUE TITLE
Next button appears on last page of results, if I click it then page breaks.

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#24]
Conduct a search, such as Pesto.  You will get 9 results.  I can page 'Next' to view results 6 - 9.  The 'Next' button still appears (it should not appear since I've reached the end of the results).  

If i click that 'Next' button on the last page, then the results change to "Number of result found 0" and I'm unable to do a new search or go back.

I think the fix is to prevent the 'Next' button from appearing on the last page of results.

**Comment by danyasamuel** [comment]
fixed by Danya

**Comment by DRTforGSA18F** [comment]
:+1:
