### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ttelenta** [DRTforGSA18F/FoodRecallGateway#25]
1) Unable to restrict advanced search to 2015 only

2) Unclear that after I enter advanced search parameters I need to click on Search again

**Comment by DRTforGSA18F** [comment]
:+1:

**Comment by danyasamuel** [comment]
Fixed #1. Looking into #2

**Comment by DRTforGSA18F** [comment]
@ttelenta not sure what #2 implies but the advanced search is not meant to perform a search. It's designed to provide additional search options. User will still have to click on the search button to perform the search. Closing this issue for now but we can discuss further, if needed.
