### ISSUE TITLE
Pyramid is too big

### ISSUE THREAD

**Issue by GeoffDick** [DRTforGSA18F/FoodRecallGateway#31]
I think the pyramid is too big.

It dominates the home screen and takes user's attention away from the main functionality - the search box.
After results, when you scroll down, the pyramid rising up is an awesome event.

On the one hand this can be considered a small issue, but perhaps we can think of a relatively inexpensive fix that preserves the functionality.

**Comment by DRTforGSA18F** [comment]
@GeoffDick I do agree the pyramid was too big. It has now been reduced to half the size it was before.
