### ISSUE TITLE
For searches with 0 results, it states "Viewing 1 to 5 of 0 results"

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#40]
If I do a search where I know I'll get 0 results, the results say "Viewing 1 to 5 of 0 results".  It should simply state "0 results."

![image](https://cloud.githubusercontent.com/assets/12449264/8331246/35914336-1a55-11e5-88f2-0e43bae3b5ec.png)

**Comment by danyasamuel** [comment]
Fixed by Danya

**Comment by DRTforGSA18F** [comment]
:+1:
