### ISSUE TITLE
Change all instances of the text "My Pyramid" to be "My Plate"

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#47]
In the section heading, it says "My Pyramid".  Please be sure to chance all references to "My Pyramid" to be "My Plate."

Locations I see:
1. Header
2. Section Title above the ChooseMyPlate image
3.  Food Pathogens USDA food pyramid  (actually, shouldn't the text, "USDA food pyramid" simply be deleted)?

**Comment by danyasamuel** [comment]
changes should be up on heroku

**Comment by DRTforGSA18F** [comment]
:+1:
