### ISSUE TITLE
Enter doesn't trigger the search

### ISSUE THREAD

**Issue by ttelenta** [DRTforGSA18F/FoodRecallGateway#52]
Search Bar
1) I search by "milk" + "strawberry" and click Enter
2) system displays results for the following search query: "milk" + "strawberry" + "cheese". This is because Enter was auto selecting the next item on the list instead of initiating the Search

Enter doesn't trigger Search.

**Comment by DRTforGSA18F** [comment]
@ttelenta  This is by design. Pressing enter is dedicated to autocomplete keywords. you will have to tab to the search button and press enter to perform a search. Again if feel differently, we can reopen this defect.
