### ISSUE TITLE
Results refresh

### ISSUE THREAD

**Issue by ttelenta** [DRTforGSA18F/FoodRecallGateway#53]
1) I searched for "apple"
2) System displayed 1 to 5 of 40 results
3) I remove "apple" from the Search bar
4) System still displays 1 to 5 of 40 results

**Comment by DRTforGSA18F** [comment]
@ttelenta if you have removed the keyword ("apple" in this case) and clicked the search button again, then this issue is fixed. However, removing the keyword alone will not refresh the results set till the second search is performed. We can re-open this defect if you have other observation.
