### ISSUE TITLE
Details Refresh

### ISSUE THREAD

**Issue by ttelenta** [DRTforGSA18F/FoodRecallGateway#54]
1) I searched for "apple"
2) System displayed 1 to 5 of 40 results
3) I clicked on the first apple related recall in the list
3) System displayed the recall details
4) I searched for "meet"
5) System displayed 1-5 of 15 results
6) I scrolled down to details section and the old apple related recall details are still there.

**Comment by DRTforGSA18F** [comment]
fixed!
