### ISSUE TITLE
Missing Static Text Updates as of 6/25/2015

### ISSUE THREAD

**Issue by stioseco** [DRTforGSA18F/FoodRecallGateway#61]
1. Year Range does not appear above the Year drop-down fields. This was outlined in the Google docs URL to add in order to ensure consistency with the labeling for States and Recall Status fields in the Advanced Search box. 

![advanced search box year range updates](https://cloud.githubusercontent.com/assets/13006268/8355363/c9f1cd6c-1b1c-11e5-80ed-f19d8134a589.png)
1. What to Do Next: The text should be converted to  FAQs or References and include the link to Weekly Enforcement Reports. Hyperlink Text: Weekly Enforcement Reports to http://www.fda.gov/safety/recalls/enforcementreports/

FAQs and Recalls: http://www.befoodsafe.org/sites/befoodsafe.org/files/FAQ%20&%20Recall%20Terms_FNL.pdf

**Comment by DRTforGSA18F** [comment]
added missing text
