### ISSUE TITLE
CRITICAL Text Updates: Food Group Box Headers and Search Descriptions

### ISSUE THREAD

**Issue by stioseco** [DRTforGSA18F/FoodRecallGateway#62]
1. Under the My Plate section, each of the header titles in the food group boxes should correspond to the food group names as displayed in the official USDA MyPlate graphic. Fruit should be updated to Fruits (plural), Grain to Grains, and Vegetable to Vegetables.
   ![food groups](https://cloud.githubusercontent.com/assets/13006268/8362232/bc9993ba-1b45-11e5-99a3-eb43fcab3ae4.PNG)
2. Search Results Display: Instructions Needed for Users 
   ![results instructions](https://cloud.githubusercontent.com/assets/13006268/8362225/af77b842-1b45-11e5-81eb-1c6a5fa8edf7.png)

MISSING: Instructions to Users to click on results records to view more detail. We want to show functionality here.

To DRT DEV TEAM: Once the list of color-coded results records appear after a user performs the Quick Search or Advanced Search, the following text should be displayed underneath ‘RESULTS’:

The results displayed below are the latest food recalls reported to FDA as of May 30, 2015. Each recall record is color-coded according to the FDA Recall Classification tiers, which are used to define the level of hazard involved for consumers. (See legend at right).  Click on the record to view more details on the recall. 
1. Advanced Search Box Window - Needs Text - "Year Range" above Year Drop-Down Fields to Match States and Recall Status Fields (Text Size, Color, etc.)
   ![advanced search box year range updates](https://cloud.githubusercontent.com/assets/13006268/8362130/2d08bece-1b45-11e5-8916-f8d3f7d72302.png)

**Comment by DRTforGSA18F** [comment]
fixed
