### ISSUE TITLE
Provide information on the classification levels in the My Plate section

### ISSUE THREAD

**Issue by chriszeiders** [DRTforGSA18F/FoodRecallGateway#63]
In the default view of the page (prior to executing a search), the My Plate section shows the severity classifications (Class I, Class II, Class III), however information describing these classifications is not visible.  (The legend--the existing place to describe the classification levels--becomes visible once a search is executed).

We propose 3 options:

Option 1: Add the Classification Tiers text (from the legend) to the right of the My Plate food boxes.
![image](https://cloud.githubusercontent.com/assets/12449264/8357227/cfefcfba-1b27-11e5-8870-e7539706e320.png)

Option 2: Add a hyperlink the word "classification" in the phrase, "The number of recalls based on classification are"  each of food boxes....and the destination of the link is  http://www.fda.gov/ForConsumers/ConsumerUpdates/ucm049070.htm#RecallClassifications 

Option 3: Keep as-is and log it as an enhancement.

**Comment by danyasamuel** [comment]
adding the link
