### ISSUE TITLE
Missing Recall Classifications Legend under MyPlate Food Groups Section

### ISSUE THREAD

**Issue by stioseco** [DRTforGSA18F/FoodRecallGateway#65]
Right now, there isn't a legend next to the food group boxes under My Plate section on the site.
As such, the class food recall counts within each box are somewhat unclear without that recall classification definition legend. 

![myplate missing class i-iii legend](https://cloud.githubusercontent.com/assets/13006268/8357023/b083d816-1b26-11e5-8d0d-c4a7964258c4.PNG)

**Comment by DRTforGSA18F** [comment]
duplicate
