### ISSUE TITLE
CRITICAL:  Footer Update

### ISSUE THREAD

**Issue by GeoffDick** [DRTforGSA18F/FoodRecallGateway#67]
Please do the following in the footer:
1.  Move "Made with love by DRT" to be align right.
2.  Put the following text align left:  "For more information contact DRT Strategies Inc., at:  www.MoreInfo@drtstrategies.com"

Thanks.

**Comment by stioseco** [comment]
@GeoffDick do you want to use the DRT official logo here? 
![drt logo hi res official](https://cloud.githubusercontent.com/assets/13006268/8363006/482bb2ce-1b4a-11e5-82bc-a930edeeb92e.jpg)

**Comment by DRTforGSA18F** [comment]
@GeoffDick @stioseco  ... closing this issue for now. If logo needs to be added, we can reopen.
